sudo: required

services:
  - docker

language: java

before_install:
  - chmod +x travis/*.sh

install: true
script: travis/install.sh

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.m2/wrapper
before_cache:
  - rm -rf $HOME/.m2/repository/com/dabsquared/gitlabjenkins
