version: '2'

services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.5-1
    ports:
      - "5432:5432"
    environment:
      - DB_USER=gitee
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
      - DB_EXTENSION=pg_trgm
    volumes:
      - /srv/docker/gitee/postgresql:/var/lib/postgresql

  gitlab:
    restart: always
    image: sameersbn/gitee:9.4.1
    depends_on:
      - redis
      - postgresql
    ports:
      - "10080:80"
      - "10022:22"
    environment:
      - DEBUG=false

      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=gitee
      - DB_PASS=password
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - TZ=Asia/Kolkata
      - GITEE_TIMEZONE=Kolkata

      - GITEE_HTTPS=false
      - SSL_SELF_SIGNED=false

      - GITEE_HOST=localhost
      - GITEE_PORT=10080
      - GITEE_SSH_PORT=10022
      - GITEE_RELATIVE_URL_ROOT=
      - GITEE_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string
      - GITEE_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
      - GITEE_SECRETS_OTP_KEY_BASE=long-and-random-alpha-numeric-string

      - GITEE_ROOT_PASSWORD=
      - GITEE_ROOT_EMAIL=

      - GITEE_NOTIFY_ON_BROKEN_BUILDS=true
      - GITEE_NOTIFY_PUSHER=false

      - GITEE_EMAIL=notifications@example.com
      - GITEE_EMAIL_REPLY_TO=noreply@example.com
      - GITEE_INCOMING_EMAIL_ADDRESS=reply@example.com

      - GITEE_BACKUP_SCHEDULE=daily
      - GITEE_BACKUP_TIME=01:00

      - SMTP_ENABLED=false
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_STARTTLS=false
    volumes:
      - /srv/docker/gitee/gitee:/home/git/data

  redis:
    restart: always
    image: sameersbn/redis:latest
    volumes:
      - /srv/docker/gitee/redis:/var/lib/redis

  jenkins:
    restart: always
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /srv/docker/jenkins:/var/jenkins_home
